name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run code formatting check (black)
      run: |
        pip install black
        black --check src/

    - name: Run linting (flake8)
      run: |
        pip install flake8
        flake8 src/

    # 향후 테스트 구현 시 활성화
    # - name: Run tests
    #   run: |
    #     pip install pytest
    #     pytest tests/